Dev
idchlife/kanal pull request #1
Opened 2023-02-16 12:42 UTC by notetell

2023-02-17 07:45 UTC, idchlife commented
@notetell please remove .idea folder

2023-02-17 07:57 UTC, idchlife requested changes
Please apply rubocop style guide and fix style errors. Also add .idea folder to .gitignore

2023-02-17 08:29 UTC, idchlife submitted a review, later dismissed

2023-02-17 12:08 UTC, idchlife commented on lib/kanal/core/helpers/response_execution_block.rb
> +          core.hooks.call :output_before_returned, input, output
Hook called :output_before_returned, but in fact it is called when output is being constructed. I think there is a better place to call this hook, instead of here

2023-02-17 12:19 UTC, idchlife commented on lib/kanal/core/router/router.rb
>          def create_output_for_input(input)
This method should be removed

2023-02-17 12:24 UTC, idchlife commented on lib/kanal/core/router/router_node.rb
>          def construct_response(input)
This method should be removed

2023-02-17 12:25 UTC, idchlife commented on lib/kanal/core/router/router_node.rb
> +          unless @response_blocks.count.positive?
Better to write .empty?

2023-02-20 12:17 UTC, notetell commented on lib/kanal/core/helpers/response_execution_block.rb
> +          core.hooks.call :output_before_returned, input, output
Maybe renaming of the hook to "output before queued" will make more sense since we don't actually "return" it now. Since this hook requires input

We can move this hook call inside ResponseExecutionBlock.execute method. For both types of response we will construct the output, then call the hook and only then we will enqueue output to output_queue.

2023-02-20 12:19 UTC, notetell commented on lib/kanal/core/helpers/response_execution_block.rb
> +          core.hooks.call :output_before_returned, input, output
`
output = construct_output(core)

core.hooks.call :output_before_returned, input, output

output_queue.enqueue output
`

2023-02-20 12:24 UTC, idchlife commented on lib/kanal/core/helpers/response_execution_block.rb
> +          core.hooks.call :output_before_returned, input, output
I think we don't need to enlighten end users about insides of the library, telling about queue and stuff.

We can't call hook in code between .construct and .enqueue because it can be ran asynchronously, and we should not force that type of execution on hooks.

For now it's better to call this hook here: https://github.com/idchlife/kanal/blob/f9133d349db30bfbb597d4f13512b94ef1dfcb7e/lib/kanal/core/router/router.rb#L31

This way it is actually before output returned.

2023-02-20 12:37 UTC, notetell commented on lib/kanal/core/helpers/response_execution_block.rb
> +          core.hooks.call :output_before_returned, input, output
We need to add argument "input" for :item_queued hook then - so we can pass the input to :output_before_returned call inside it.

2023-03-01 07:32 UTC, idchlife commented on lib/kanal/core/helpers/response_execution_block.rb
> +          core.hooks.call :output_before_returned, input, output
In the end after several discussions it is agreed upon - we should leave it at that. We call this hook inside ResponseExecutionBlock

2023-03-01 13:36 UTC, idchlife approved these changes

2023-03-01 13:36 UTC, merged