Reply markup
idchlife/kanal pull request #13
Opened 2023-03-20 08:16 UTC by notetell

2023-03-20 11:33 UTC, idchlife requested changes

2023-03-20 11:33 UTC, idchlife commented on lib/kanal/core/helpers/parameter_finder_with_method_missing_mixin.rb
We don't need to accept block here because block will be accepted only if some parameter is passed with it.

Meaning it's basically useless feature.

We can pass block only like:

```rb
respond do
  my_param 123 do
    # block code
  end
end
```

Considering we save parameters inside key=>value collection, we can't store value1/value2 without creating additional wrapper class. Which we won't do for the sake of simplicity.

2023-03-20 11:33 UTC, idchlife commented on lib/kanal/plugins/batteries/keyboard.rb
We don't need attr_reader here for :layout. It's not used

2023-03-20 11:33 UTC, idchlife commented on lib/kanal/plugins/batteries/keyboard.rb
Add Yard doc for methods and class

2023-03-20 12:19 UTC, notetell commented on lib/kanal/core/helpers/parameter_finder_with_method_missing_mixin.rb
Got rid of passing block to [lib/kanal/core/helpers/parameter_finder_with_method_missing_mixin.rb](https://github.com/idchlife/kanal/pull/13/files/dab23e28488d2772f3c4cab63bcd5f2b49bad5bd#diff-76d560526d91302be653ac54d2842d459faea69182f8b3121df61fca41dc9dde)

2023-03-20 12:26 UTC, notetell commented on lib/kanal/plugins/batteries/keyboard.rb
Added.

2023-03-20 12:47 UTC, idchlife requested changes

2023-03-20 19:53 UTC, idchlife commented on lib/kanal/plugins/batteries/keyboard.rb
8. Do not write parameter description in <>, write in plain text

2023-03-21 10:27 UTC, idchlife requested changes

2023-03-21 10:27 UTC, idchlife commented on lib/kanal/plugins/batteries/keyboard.rb
>          # keyboard.from array [["B1", "B2"], ["B3"]]
Forgot the _

```suggestion
        # keyboard.from_array [["B1", "B2"], ["B3"]]
```

2023-03-21 10:29 UTC, notetell commented on lib/kanal/plugins/batteries/keyboard.rb
>          # keyboard.from array [["B1", "B2"], ["B3"]]
Done https://github.com/idchlife/kanal/commit/6c165fbd8e0845627c519d7a3a532a2b8813951c

2023-03-21 10:35 UTC, idchlife approved these changes

2023-03-21 10:35 UTC, merged