Logging
idchlife/kanal pull request #18
Opened 2023-03-21 13:41 UTC by notetell

2023-03-21 17:27 UTC, idchlife requested changes

2023-03-21 17:27 UTC, idchlife commented on lib/kanal/core/core.rb
> +        Configuration.add_logger logger
```suggestion
        Kanal::Core::Logging::Configuration.add_logger logger
```

2023-03-22 08:27 UTC, notetell commented on lib/kanal/core/logging/composite_logger.rb
> +            logger.progname = self.class.name.rpartition(':').last
Added comments.

This bit with self.class.name didn't work since earlier it was used inside module method, and now it is a class method. It works now.

`
caller_class_name = caller[0].split(".rb").first.split("/").last.split('_').collect(&:capitalize).join

raise "Wrong method called for CompositeLogger" unless @allowed_methods.include? method

@loggers.each do |logger|
  logger.progname = caller_class_name
  logger.send method, message
end
`

2023-03-22 08:51 UTC, idchlife requested changes

2023-03-22 08:51 UTC, idchlife commented on lib/kanal/core/logging/composite_logger.rb
> +        #
```suggestion
```

Test remove line

2023-03-22 09:10 UTC, notetell commented on lib/kanal/core/logging/composite_logger.rb
> +            logger.progname = self.class.name.rpartition(':').last
Wrapped getting caller class name in begin-rescue, added proper comments. https://github.com/idchlife/kanal/pull/18/commits/fc95b99a17941020f750f49452c6aadf7c150e42

2023-03-22 09:34 UTC, merged