Output processing remake
idchlife/kanal pull request #37
Opened 2023-04-12 08:36 UTC by notetell

2023-04-13 07:32 UTC, idchlife requested changes

2023-04-13 07:32 UTC, idchlife commented on lib/kanal/core/helpers/input_output_pair.rb
Add Yard doc

2023-04-13 07:32 UTC, idchlife commented on lib/kanal/core/helpers/response_execution_block.rb
> +          InputOutputPair.new @input, output
This method simply constructs output and not expected to return pair. Move construction of pair where pair exists already

2023-04-13 11:24 UTC, notetell commented on lib/kanal/core/helpers/response_execution_block.rb
> +          InputOutputPair.new @input, output
Done https://github.com/idchlife/kanal/pull/37/commits/6744b362afd37dd832e385eb321e4048c0ff135d

2023-04-13 11:42 UTC, notetell commented on lib/kanal/core/helpers/input_output_pair.rb
https://github.com/idchlife/kanal/pull/37/commits/6de0d1e50d3d63b689377a672baf2b83ece8411c

2023-04-13 12:26 UTC, idchlife requested changes

2023-04-13 12:26 UTC, idchlife commented on lib/kanal/core/helpers/response_execution_block.rb
> +              core.router.input_output_pair @input, construct_output(core)
Why pass to router method if you have queue here?

2023-04-13 12:26 UTC, idchlife commented on lib/kanal/core/router/router.rb
> +        def input_output_pair(input, output)
Method name is very abstract and seems like simple property

Better rename it to `provide_output_with_input(output, input)`

2023-04-13 12:26 UTC, idchlife commented on lib/kanal/core/router/router.rb
> +          begin
no need to protect this part because problems with output processing should be managed by upper level code, which uses `.output_ready do |output| end`

2023-04-14 15:17 UTC, idchlife requested changes

2023-04-14 15:17 UTC, idchlife commented on lib/kanal/core/router/router.rb
> +        # This method adds input-output pair into input_output_pair_queue for it to be processed in item_queued hook
```suggestion
        # Method allows to pass output with input directly to the end step,
        # when outputs are processed after router. Meaning it will not go
        # through router, but will have all hooks in :output_before_returned executed for it.
        # Input is needed for hooks to work properly.
        #
        # WARNING: this method AVOIDS router whatsoever
        # Why use this method? If you want router to give out (through output_ready(&block) method) output without
        # passing through router but with hooks called (many plugins use hooks to alter the output) - you
        # use this method.
        #
        # This method adds input-output pair into input_output_pair_queue for it to be processed in item_queued hook
```

2023-04-14 15:17 UTC, idchlife commented on lib/kanal/core/router/router.rb
> +        # This method calls output_ready_block on pre-formed output right away
```suggestion
        # Method allows to pass output directly to the end output
        # consumer (code which uses .output_ready(&block). Without passing router and
        # without passing hooks attached to :output_before_ready
        #
        # WARNING: output provided via this method will avoid any alteration by the
        # router inner machinery and will go directly to the output consumer
        #
        # Why use this method? If you want to pass output with your manually defined
        # properties to the output consumer (which uses .output_ready(&block))
        # without any alternations by the router system.
        #
        # This method calls output_ready_block on pre-formed output right away
```

2023-04-14 15:17 UTC, idchlife commented on lib/kanal/core/router/router.rb
> +          _input_output_pair_queue = @input_output_pair_queue
```suggestion
          _input_output_pair_queue = @input_output_pair_queue
          # Attaching to the queue hook to capture enqueued output and move it
          # forward in the workflow: apply hooks in :output_before_ready and pass it to
          # the end consumer which uses .output_ready(&block)
```

2023-04-14 15:19 UTC, idchlife requested changes

2023-04-14 15:19 UTC, idchlife commented on lib/kanal/core/router/router.rb
> +        # param [Kanal::Core::Output] output <description>
Type definitions are off. Please check all the places also for proper types. There is no class Kanal::Core::Output

2023-04-14 17:32 UTC, idchlife approved these changes

2023-04-14 17:32 UTC, merged