Create router method to get beautified string for routes for overview and debug purpose
idchlife/kanal pull request #53
Opened 2023-04-17 15:17 UTC by notetell

2023-04-18 07:59 UTC, notetell commented
Please review. PS: call for print_config right now is in router_spec's first case.

2023-04-24 07:21 UTC, idchlife requested changes

2023-04-24 07:21 UTC, idchlife commented on lib/kanal/core/router/router.rb
> +        def configuration_string
Better rename it to `routes_info_string`

2023-04-24 07:29 UTC, idchlife approved these changes

2023-04-24 13:28 UTC, merged