Attachments
idchlife/kanal pull request #7
Opened 2023-03-13 16:40 UTC by notetell

2023-03-14 07:15 UTC, idchlife requested changes
FileCreator should not be inside Kanal Core. Right now this class is not used inside Core.

What is method save_file_with_random_name?

2023-03-14 07:20 UTC, notetell commented
Fixed wrong method call. 

FileCreator is a general helper that might be useful in the future for any file saving needs. Where to put it if not in the core where any plugin or interface can access it?

2023-03-14 07:23 UTC, idchlife commented
> Fixed wrong method call. 
> 
> 
> 
> FileCreator is a general helper that might be useful in the future for any file saving needs. Where to put it if not in the core where any plugin or interface can access it?

We use approach - don't store it if it's not used right now. Otherwise we could end up with tons of helpers, utilities, which used by outside plugins and not the core.

Considering this feature used ONCE, I suggest to scrap whole helper and just write code inside batteries plugin, where it's needed. If it's used once - no need to put it in separate module, class. Simple method nearby will do.

2023-03-14 07:54 UTC, idchlife requested changes

2023-03-14 07:54 UTC, idchlife commented on lib/kanal/plugins/batteries/attachments/attachment.rb
> +          def save(dir_path, extension, length = 32)
1) We should be able to save file and call it whatever we want, event without extension
2) What is length? It is unclear what this argument is about and what does it do, looking into this method body
3) Many methods in this class should not be public

2023-03-14 08:00 UTC, notetell commented
1. Maybe leave extension as optional argument with default nil? So we can provide .png to pics, .mp3 for audio etc.
2 and 3 noted

2023-03-14 08:20 UTC, idchlife commented
> 1. Maybe leave extension as optional argument with default nil? So we can provide .png to pics, .mp3 for audio etc.
>    2 and 3 noted

Developer writing responses and saving files could provide the needed extension.

Generally the thing with "saving files that came from somewhere outside" is a controversial thing.

I mean we could and maybe should provide helper methods in base attachment like:

.audio?
.mp3?
.wav?
.ogg?

.document?
.doc?
.docx?
.odf?

.image?
.jpg?
.png?
.bpm?
.gif?

.video?
.mp4?
.mov?
.mkv?

And possibly method like

.extension - which would get extension by file url

All of this methods helpers should use the BASIC check for extension, meaning - parse url, get the filename if there is any, and get extension by simply "get something after . and before the rest of query parameters".
Example:

myurl.com/files/download/bots/filename-md5-hash-3234324.jpg?also-some-id=42&hey=whatsgoingon

This one will be parsed and .extension method will give "jpg"

Because we cannot determine otherwise without saving it.

Methods helpers for popular extensions and filetypes will be useful for developer writing responses.

Also, considering the whole structure, I don't think we will need separate classes like ImageAttachment, AudioAttachment etc, because the visual separation happens inside response block. Meaning inside input.audio will be simply "Attachment". No need to create subclasses, because there won't be any checks inside response block. Right now I can't imagine developer doing `if input.audio.is_a? AudioAttachment" because it is already in input.audio property.

But helper methods can help developer utilise which extension to use without boilerplate code for checking extension by url themselves.

In the end I suggest:

1) Remove subclasses for attachment, leave only Attachment
2) Add helper methods, public
3) Use save method like save(path) and that's it (no return value)
4) Make url - public property of Attachment, developer should be able to work with url directly, if needed
5) Create quick_save(dir_path) method which would try to guess extension, use it, save in provided dir_path, and also use random name for file. Returned value - filename.
6) Write Yard docs for methods with explanation of arguments and return parameters

2023-03-15 11:05 UTC, idchlife requested changes

2023-03-15 11:05 UTC, idchlife commented on lib/kanal/plugins/batteries/attachments/attachment.rb
1) Unnecessary encapsulation of File.mkdir. Method create_directory is redundant. Use File.mkdir directly in the code
2) Make methods that should not be visible publicly - private.
3) Allow quick_save to save file without extension. Lack of extension is not a problem.

2023-03-15 13:42 UTC, idchlife requested changes

2023-03-15 13:42 UTC, idchlife commented on lib/kanal/plugins/batteries/attachments/attachment.rb
>              rescue
This whole begin/rescue code is dangerous. If there is no access to filesystem, or folder does not exist - code will result in infinite loop. Better check if file exists already at chosen path and if yes - call this function again. That is all.

2023-03-15 13:42 UTC, idchlife commented on lib/kanal/plugins/batteries/attachments/attachment.rb
>            def save_file(content, filepath)
We should not create directories for the end developer without asking.

This could result in an unexpected behaviour.
If developer mistyped a letter - files would end up in wrong directory.

Better provide argument in save(path, create_dirs = false) and use it here.

Also, name of method better to rename to save_stream_to_file, right now method name is too vague and looks like first argument should be a file or something and also near the method "save" and "quick_save" it looks too confusing.

2023-03-15 14:51 UTC, idchlife requested changes

2023-03-15 14:51 UTC, idchlife commented on lib/kanal/plugins/batteries/attachments/attachment.rb
> +            quick_save directory, filename_length if File.exist? filename
After going into recursion code will continue execution of saving even existing file. Meaning overwriting it. Please fix.

2023-03-15 14:51 UTC, idchlife commented on lib/kanal/plugins/batteries/attachments/attachment.rb
> +          def save(filepath, create_dirs = false)
Add yard doc for new argument

2023-03-15 15:46 UTC, idchlife approved these changes

2023-03-15 16:23 UTC, merged